### ISSUE TITLE
Link to 404 in Tutorial

### ISSUE THREAD

**Issue by AlexanderFillbrunn** [datamininggroup/pfa#3]
Hi,
I just noticed that on the page http://dmg.org/pfa/docs/tutorial2/ the link to the exoplanets example is http://dmg.org/docs/exoplanets, but should be http://dmg.org/pfa/docs/exoplanets/.

**Comment by wwells** [comment]
Good catch.  Issue resolved.   New html generated from .md, live site updated.   https://github.com/datamininggroup/pfa-docs/blob/master/docs/tutorial2.md
