### ISSUE TITLE
Git LFS – Trouble pulling down conformance tests

### ISSUE THREAD

**Issue by jnicholls** [datamininggroup/pfa#6]
GitHub [moved the conformance tests](https://github.com/datamininggroup/pfa/blob/master/conformance-tests/pfa-tests.json) to [Git LFS](https://git-lfs.github.com/) storage since it is a very large file.  However, I am having trouble pulling the file down with `git lfs` extension.  I am receiving the following:

```bash
~/Code/pfa (master)$ git lfs pull origin master
Git LFS: (0 of 1 files, 1 skipped) 0 B / 238.24 MB, 238.24 MB skipped
[404] Object does not exist on the server
[64d83b7dfa013c4193b2f9743f8a40e1ea20d9dede879ccead653df074c7906c] Object does not exist on the server
```

Basically it thinks the file doesn't exist on the GitHub LFS server.  Any thoughts?  Am I the only one having this issue?

**Comment by collinbennett** [comment]
A few of us have had trouble with Git LFS.  We will completely replace it soon.

The link on the DMG site works: http://github.com/datamininggroup/pfa/releases/download/0.8.1/pfa-tests.json

**Comment by collinbennett** [comment]
I've updated the file to have a proper link instead the the GIT LFS.
